# Generated by Django 4.0.2 on 2022-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('descendants', models.CharField(max_length=4)),
                ('score', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=100, null=True)),
                ('time', models.CharField(default='', max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Askstories',
            },
        ),
        migrations.CreateModel(
            name='Jobstory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=100, null=True)),
                ('time', models.CharField(default='', max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=100, null=True)),
                ('url', models.URLField(default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jobstories',
            },
        ),
        migrations.CreateModel(
            name='Newstory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('descendants', models.CharField(max_length=4)),
                ('score', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=100, null=True)),
                ('time', models.CharField(default='', max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=100, null=True)),
                ('url', models.URLField(default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Newstories',
            },
        ),
        migrations.CreateModel(
            name='Showstory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('by', models.CharField(max_length=100)),
                ('descendants', models.CharField(max_length=4)),
                ('score', models.CharField(max_length=100)),
                ('text', models.TextField(default='', max_length=100, null=True)),
                ('time', models.CharField(default='', max_length=10, null=True)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('type', models.CharField(default='', max_length=100, null=True)),
                ('url', models.URLField(default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Showstories',
            },
        ),
    ]
