# Generated by Django 4.0.2 on 2022-02-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopbasked_alter_product_id_delete_basket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbasked',
            name='products',
        ),
        migrations.AddField(
            model_name='shopbasked',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
